prova: prova.o coordinate.o math.o room.o union_find.o
	g++ prova.o coordinate.o math.o room.o union_find.o -o prova

prova.o: prova.cpp
	g++ prova.cpp -c
coonrdinate.o: coonrdinate.cpp
	g++ coonrdinate.cpp -c
math.o: math.cpp
	g++ math.cpp -c
room.o: room.cpp
	g++ room.cpp -c
union_find.o: union_find.cpp
	g++ union_find.cpp -c



clean:
	rm *.o prova prova.exe